name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true
        type: string

jobs:
  release:
    runs-on: macOS-12
    steps:

      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: EbrahimTahernejad/chisel-mobile
          path: 'chisel'
          
      - name: Setup Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.21'
      
      - name: Setup Gomobile
        run: |
          go install github.com/sagernet/gomobile/cmd/gomobile@latest
          gomobile init
          
      - name: Build xcframework
        run: |
          cd chisel
          make apple
          cd build
          zip -ry ./Chisel.xcframework.zip ./Chisel.xcframework
          
      - name: Render Template
        run: |
          export TEMP=`shasum -a 256 chisel/build/Chisel.xcframework.zip`
          export CHECKSUM=${TEMP:0:64}
          cd Templates
          sed -i "_bak" "s/VERSION/${{ github.event.inputs.version }}/g" Package.template
          sed -i "_bak" "s/CHECKSUM/${CHECKSUM}/g" Package.template
          
      - name: Update Package.swift
        run: |
          rm -f Package.swift
          cp ./Templates/Package.template Package.swift
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Chisel Release ${{ github.event.inputs.version }}!!!
          commit_user_name: Ebrahim Tahernejad
          commit_user_email: ebrahimtahernejad@gmail.com
          tagging_message: ${{ github.event.inputs.version }}
          file_pattern: 'Package.swift'
          
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          files: chisel/build/Chisel.xcframework.zip
